# Generated by Django 3.2.2 on 2021-05-07 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('sport', models.CharField(choices=[('MLB', 'Baseball'), ('NHL', 'Hockey')], default=('MLB', 'Baseball'), max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('betting_line', models.IntegerField()),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BBET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('sport', models.CharField(choices=[('MLB', 'Baseball'), ('NHL', 'Hockey')], default=('MLB', 'Baseball'), max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('betting_line', models.IntegerField()),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CBET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('sport', models.CharField(choices=[('MLB', 'Baseball'), ('NHL', 'Hockey')], default=('MLB', 'Baseball'), max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('betting_line', models.IntegerField()),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DBET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('sport', models.CharField(choices=[('MLB', 'Baseball'), ('NHL', 'Hockey')], default=('MLB', 'Baseball'), max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('betting_line', models.IntegerField()),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('a_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.abet')),
                ('b_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bbet')),
                ('c_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cbet')),
                ('d_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dbet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
