# Generated by Django 3.2.2 on 2021-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A Bet'), ('B', 'B Bet'), ('C', 'C Bet'), ('D', 'D Bet')], default='A', max_length=50, verbose_name='type')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('sport', models.CharField(choices=[('MLB', 'Baseball'), ('NHL', 'Hockey')], default=('MLB', 'Baseball'), max_length=3)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('betting_line', models.IntegerField()),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='bettrack',
            name='a_bet',
        ),
        migrations.RemoveField(
            model_name='bettrack',
            name='b_bet',
        ),
        migrations.RemoveField(
            model_name='bettrack',
            name='c_bet',
        ),
        migrations.RemoveField(
            model_name='bettrack',
            name='d_bet',
        ),
        migrations.RemoveField(
            model_name='bettrack',
            name='user',
        ),
        migrations.DeleteModel(
            name='ABET',
        ),
        migrations.DeleteModel(
            name='BBET',
        ),
        migrations.DeleteModel(
            name='BetTrack',
        ),
        migrations.DeleteModel(
            name='CBET',
        ),
        migrations.DeleteModel(
            name='DBET',
        ),
    ]
