# Generated by Django 3.2.2 on 2021-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210510_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_track',
        ),
        migrations.AlterField(
            model_name='bet',
            name='end',
            field=models.DateField(),
        ),
    ]
